2024-11-07 00:11:31,438 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "c:\Users\ZV\Desktop\python\homework_urban\module_12\module_12_4.py", line 9, in test_walk
    piple1 = rt.Runner("Timur", -5)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ZV\Desktop\python\homework_urban\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
